# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('ótimo', 'Ótimo'), ('bom', 'Bom'), ('ruim', 'Ruim')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('telefone', 'Telefone'), ('email', 'Email'), ('facebook', 'Facebook')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pe', 'PE'), ('ac', 'AC'), ('al', 'AL'), ('am', 'AM'), ('ap', 'AP'), ('ba', 'BA'), ('ce', 'CE'), ('df', 'DF'), ('es', 'ES'), ('go', 'GO'), ('ma', 'MA'), ('mg', 'MG'), ('ms', 'MS'), ('mt', 'MT'), ('pa', 'PA'), ('pb', 'PB'), ('pi', 'PI'), ('pr', 'PR'), ('rj', 'RJ'), ('rn', 'RN'), ('ro', 'RO'), ('rr', 'RR'), ('rs', 'RS'), ('sc', 'SC'), ('se', 'SE'), ('sp', 'SP'), ('to', 'TO')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.CharField(max_length=9, verbose_name='Valor da Compra')),
                ('valor_venda', models.CharField(max_length=9, verbose_name='Valor da Venda')),
                ('quantidade', models.CharField(max_length=9, verbose_name='Quantidade')),
                ('taxa_lucro', models.CharField(max_length=9, verbose_name='Taxa de Lucro')),
                ('especificacao', models.CharField(max_length=100, verbose_name='Especificacao')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Estoque',
                'verbose_name': 'Estoque',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('tipo_fornecimento', models.CharField(max_length=100, verbose_name='Tipo de Fornecimento')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
            ],
            options={
                'verbose_name_plural': 'Fornecedores',
                'verbose_name': 'Fornecedor',
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=7, verbose_name='RG')),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], max_length=20)),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('separado', 'Separado'), ('divorciado', 'Divorciado'), ('viúvo', 'Viúvo')], max_length=20, verbose_name='Estado Civil')),
                ('nome_pai', models.CharField(max_length=255, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(max_length=255, verbose_name='Nome da Mãe')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('data_adimicao', models.DateField(verbose_name='Data de Adimição')),
                ('numero_ctps', models.CharField(max_length=11, verbose_name='Número CTPS')),
                ('numero_pis', models.CharField(max_length=11, verbose_name='Número do PIS')),
                ('tipo', models.CharField(choices=[('fichado', 'Fichado'), ('experiência', 'Experiência'), ('diarista', 'Diarista')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=9, verbose_name='Quantidade')),
                ('tipo', models.CharField(max_length=9, verbose_name='Tipo')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
                'verbose_name': 'Produto',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=9, verbose_name='Valor')),
                ('data_de_venda', models.CharField(max_length=9, verbose_name='Data de Venda')),
                ('quantidade', models.CharField(max_length=9, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name_plural': 'Vendas',
                'verbose_name': 'Venda',
            },
        ),
        migrations.AddField(
            model_name='endereco',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Funcionario'),
        ),
        migrations.AddField(
            model_name='contato',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Funcionario'),
        ),
    ]
