# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Acessorio',
        ),
        migrations.RemoveField(
            model_name='contato',
            name='funcionario',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='funcionario',
        ),
        migrations.DeleteModel(
            name='Estoque',
        ),
        migrations.DeleteModel(
            name='Fornecedor',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
        migrations.DeleteModel(
            name='Contato',
        ),
        migrations.DeleteModel(
            name='Endereco',
        ),
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
