# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180305_1518'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=7, verbose_name='RG')),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], max_length=20)),
                ('estado_civil', models.CharField(choices=[('solteiro', 'Solteiro'), ('casado', 'Casado'), ('separado', 'Separado'), ('divorciado', 'Divorciado'), ('viúvo', 'Viúvo')], max_length=20, verbose_name='Estado Civil')),
                ('nome_pai', models.CharField(max_length=255, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(max_length=255, verbose_name='Nome da Mãe')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('data_adimicao', models.DateField(verbose_name='Data de Adimição')),
                ('numero_ctps', models.CharField(max_length=11, verbose_name='Número CTPS')),
                ('numero_pis', models.CharField(max_length=11, verbose_name='Número do PIS')),
                ('tipo', models.CharField(choices=[('fichado', 'Fichado'), ('experiência', 'Experiência'), ('diarista', 'Diarista')], max_length=20)),
            ],
        ),

    ]
