# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180305_1520'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255)),
                ('numero', models.IntegerField()),
                ('bairro', models.CharField(max_length=50)),
                ('complemento', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('pe', 'PE'), ('ac', 'AC'), ('al', 'AL'), ('am', 'AM'), ('ap', 'AP'), ('ba', 'BA'), ('ce', 'CE'), ('df', 'DF'), ('es', 'ES'), ('go', 'GO'), ('ma', 'MA'), ('mg', 'MG'), ('ms', 'MS'), ('mt', 'MT'), ('pa', 'PA'), ('pb', 'PB'), ('pi', 'PI'), ('pr', 'PR'), ('rj', 'RJ'), ('rn', 'RN'), ('ro', 'RO'), ('rr', 'RR'), ('rs', 'RS'), ('sc', 'SC'), ('se', 'SE'), ('sp', 'SP'), ('to', 'TO')], max_length=20)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Funcionario')),
            ],
        ),
    ]
