# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('ótimo', 'Ótimo'), ('bom', 'Bom'), ('ruim', 'Ruim')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contato', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('telefone', 'Telefone'), ('email', 'Email'), ('facebook', 'Facebook')], max_length=20)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.CharField(max_length=9, verbose_name='Valor da Compra')),
                ('valor_venda', models.CharField(max_length=9, verbose_name='Valor da Venda')),
                ('quantidade', models.CharField(max_length=9, verbose_name='Quantidade')),
                ('taxa_lucro', models.CharField(max_length=9, verbose_name='Taxa de Lucro')),
                ('especificacao', models.CharField(max_length=100, verbose_name='Especificacao')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoque',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('tipo_fornecimento', models.CharField(max_length=100, verbose_name='Tipo de Fornecimento')),
                ('cnpj', models.CharField(max_length=20, verbose_name='CNPJ')),
                ('telefone', models.CharField(max_length=100, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=9, verbose_name='Valor')),
                ('data_locacao', models.DateField(verbose_name='Data de Início')),
                ('data_entrega', models.DateField(verbose_name='Data de Fim')),
            ],
            options={
                'verbose_name': 'Locação',
                'verbose_name_plural': 'Locações',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.CharField(max_length=9, verbose_name='Quantidade')),
                ('tipo', models.CharField(max_length=9, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('marca', models.CharField(max_length=20)),
                ('placa', models.CharField(max_length=8)),
                ('cor', models.CharField(choices=[('preto', 'Preto'), ('azul', 'Azul'), ('amarelo', 'Amarelo'), ('branco', 'Branco'), ('prata', 'Prata'), ('vermelho', 'Vermelho')], max_length=20)),
                ('ano', models.IntegerField()),
                ('preco', models.FloatField()),
                ('tipo', models.CharField(choices=[('moto', 'Moto'), ('carro', 'Carro'), ('caminhão', 'Caminhão'), ('máquina', 'Máquina')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=9, verbose_name='Valor')),
                ('data_de_venda', models.CharField(max_length=9, verbose_name='Data de Venda')),
                ('quantidade', models.CharField(max_length=9, verbose_name='Quantidade')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
            },
        ),
        migrations.AddField(
            model_name='locacao',
            name='veiculo',
            field=models.ManyToManyField(to='app.Veiculo'),
        ),
    ]
