# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-03-05 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='cliente',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Cliente'),
            preserve_default=False,
        ),
    ]
